/** @type {import('typedoc').TypeDocOptions} */
const options = {
  // readme
  entryPoints: ['./src/index.ts'],
  out: 'docs',
  validation: {
    notDocumented: true,
  },
  treatWarningsAsErrors: true,
  excludePrivate: true,
  categoryOrder: [
    'Client',
    'Client Params',
    'Wallet',
    'Wallet Impl',
    'Smart Wallet',
    'Smart Wallet Impl',
    'Wallet Util',
    'Chain Provider',
    'Chain Provider Impl',
    'Crypto Source',
    'Crypto',
    'Crypto Approve',
    'Crypto Approve Impl',
    'Crypto Aggregator',
    'Chain',
    'Quote',
    'Swap',
    'Swap Approve',
    'Swap Submit',
    'Amount',
    'Amount Source',
    'Explorer',
    'Contract',
    'Collateral Contract',
    'Transaction',
    'Resolver',
    'Instant',
    'Duration',
    'Math',
    'Native',
    'Bitcoin',
    'Data',
    'API',
    'Util',
    'EVM Provider',
    'EVM Provider Impl',
    'EVM Provider Config',
    '*',
  ],
  excludeExternals: true,
  externalPattern: [],
};
export default options;
