name: Publish Flash SDK
run-name: Publish Flash SDK ${{ github.event.release.tag_name }} (by ${{ github.actor }})

on:
  release:
    types: [published]

jobs:
  publish:
    name: Check, Build, Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      # Version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read package version
        id: package
        run: |
          VERSION=$(awk '/"version":/' package.json | sed 's/.*:.*"\(.*\)",/\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check release version
        run: '[ "v${{ steps.package.outputs.version }}" = "${{ github.event.release.tag_name }}" ]'

      - name: Select NPM package tag
        id: npm
        run: |
          TAG=$([[ "${{ steps.package.outputs.version }}" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] && echo "latest" || echo "next")
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Name artifact
        id: artifact
        run: |
          NAME=flash-sdk-${{ github.event.release.tag_name }}.tgz
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      # Install

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          scope: '@swaps-io'

      - name: Install dependencies
        run: yarn install --immutable

      # Build

      - name: Build artifact
        run: yarn pack --filename ${{ steps.artifact.outputs.name }}

      - name: Generate docs
        # if: ${{ steps.npm.outputs.tag == 'latest' }} -- temp
        run: |
          yarn docs:gen
          tar -czvf docs.tar.gz docs

      # Publish

      - name: Attach artifact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{ steps.artifact.outputs.name }}

      - name: Configure docs SSH
        # if: ${{ steps.npm.outputs.tag == 'latest' }} -- temp
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DOCS_CONFIG }}" >> ~/.ssh/config
          echo "${{ secrets.SSH_DOCS_KEY }}" >> ~/.ssh/sdk-docs-key
          chmod 400 ~/.ssh/sdk-docs-key
          echo "${{ secrets.SSH_DOCS_KNOWN }}" >> ~/.ssh/known_hosts

      - name: Publish docs
        # if: ${{ steps.npm.outputs.tag == 'latest' }} -- temp
        run:
          scp docs.tar.gz sdk-docs:content
          ssh sdk-docs "cd content; ./run.sh"

      - name: Publish NPM package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish ${{ steps.artifact.outputs.name }} --tag ${{ steps.npm.outputs.tag }} --access public
