name: Publish Flash SDK
run-name: Publish Flash SDK ${{ github.event.release.tag_name }} (by ${{ github.actor }})

on:
  release:
    types: [published]

jobs:
  publish:
    name: Check, Build, Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Read package version
        id: package
        run: |
          VERSION=$(awk '/"version":/' package.json | sed 's/.*:.*"\(.*\)",/v\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check release version
        run: '[ "${{ steps.package.outputs.version }}" = "${{ github.event.release.tag_name }}" ]'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          scope: '@swaps-io'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Name artifact
        id: artifact
        run: |
          NAME=flash-sdk-${{ steps.package.outputs.version }}.tgz
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Build artifact
        run: yarn pack --filename ${{ steps.artifact.outputs.name }}

      - name: Attach artifact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{ steps.artifact.outputs.name }}

      - name: Publish artifact to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish ${{ steps.artifact.outputs.name }} --tag ${{ steps.package.outputs.version }} --access public
